name: "Deploy App"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Get Code"
        uses: actions/checkout@v3

      - name: "Install NodeJs"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: "Install Dependencies"
        run: npm install

      - name: "Run Lint"
        run: npm run lint

      - name: "Run Tests"
        run: npm run test

      - name: "Run Build"
        run: npm run build